/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenasIndexRouteImport } from './routes/arenas.index'
import { Route as ArenasArenaIdRouteImport } from './routes/arenas.$arenaId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasIndexRoute = ArenasIndexRouteImport.update({
  id: '/arenas/',
  path: '/arenas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenasArenaIdRoute = ArenasArenaIdRouteImport.update({
  id: '/arenas/$arenaId',
  path: '/arenas/$arenaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/settings': typeof SettingsRoute
  '/arenas/$arenaId': typeof ArenasArenaIdRoute
  '/arenas/': typeof ArenasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/settings': typeof SettingsRoute
  '/arenas/$arenaId': typeof ArenasArenaIdRoute
  '/arenas': typeof ArenasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/settings': typeof SettingsRoute
  '/arenas/$arenaId': typeof ArenasArenaIdRoute
  '/arenas/': typeof ArenasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/settings'
    | '/arenas/$arenaId'
    | '/arenas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/settings'
    | '/arenas/$arenaId'
    | '/arenas'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/settings'
    | '/arenas/$arenaId'
    | '/arenas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  SettingsRoute: typeof SettingsRoute
  ArenasArenaIdRoute: typeof ArenasArenaIdRoute
  ArenasIndexRoute: typeof ArenasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas/': {
      id: '/arenas/'
      path: '/arenas'
      fullPath: '/arenas/'
      preLoaderRoute: typeof ArenasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arenas/$arenaId': {
      id: '/arenas/$arenaId'
      path: '/arenas/$arenaId'
      fullPath: '/arenas/$arenaId'
      preLoaderRoute: typeof ArenasArenaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  SettingsRoute: SettingsRoute,
  ArenasArenaIdRoute: ArenasArenaIdRoute,
  ArenasIndexRoute: ArenasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
